### ISSUE TITLE
Do this  work for tracking？

### ISSUE THREAD

**Issue by dd-rongfa** [Koldim2001/YOLO-Patch-Based-Inference#11]
Do this work for tracking, in yolov8?
It would be great if there were examples of object tracking。pls

**Comment by Koldim2001** [comment]
The classic model.track from the ultralytics package will not be supported due to the different format of the algorithm's output data. However, nothing prevents the use of any open-source tracker. For any tracker (for example, [bytetreck](https://github.com/ifzhang/ByteTrack)), the input requires adding the coordinates of the boxes, confidence values, and sometimes the values of the classes themselves. Here's how you can get these parameters from the output of Patch-Based-Inference:
```
confidences = result.filtered_confidences
boxes = result.filtered_boxes
classes_ids = result.filtered_classes_id
```
