### ISSUE TITLE
memory_optimize=False yields no results 

### ISSUE THREAD

**Issue by Marvin1412** [Koldim2001/YOLO-Patch-Based-Inference#13]
Using the following code I only get emtpy polygons if memory_optimize is set to False. Otherwise I yield good results. Any Idea why? I'd also be interested what your POV is on the different paramters and what is optimal if I really try to not overlook something? Greetings and Thank you!

element_crops = MakeCropsDetectThem(
    imgsz =800,
    image=left_image,
    model_path="yolov8m-seg.pt",
    segment=True,
    show_crops=False,
    shape_x=400,
    shape_y=400,
    overlap_x=10,
    overlap_y=10,
    conf=0.5,
    iou=0.9,
    memory_optimize=False,
    classes_list = list(range(80)),
    resize_initial_size=True,
)
result = CombineDetections(element_crops, nms_threshold=0.5, match_metric='IOS')

visualize_results(
    img=result.image,
    confidences=result.filtered_confidences,
    boxes=result.filtered_boxes,
    polygons=result.filtered_polygons,
    classes_ids=result.filtered_classes_id,
    classes_names=result.filtered_classes_names,
    segment=True,
    thickness=8,
    font_scale=1.1,
    fill_mask=True,
    show_boxes=False,
    delta_colors=3,
    show_class=False,
    axis_off=False
)

**Comment by Koldim2001** [comment]
Try:

visualize_results(
img=result.image,
confidences=result.filtered_confidences,
boxes=result.filtered_boxes,
masks=result.filtered_masks,
classes_ids=result.filtered_classes_id,
classes_names=result.filtered_classes_names,
segment=True,
thickness=8,
font_scale=1.1,
fill_mask=True,
show_boxes=False,
delta_colors=3,
show_class=False,
axis_off=False
)

The reason is that when working with a more accurate mask inference mode, all processing is carried out in masks, not polygons (therefore, you need to feed the visualization function masks=result.filtered_masks)

**Comment by Koldim2001** [comment]
https://github.com/Koldim2001/YOLO-Patch-Based-Inference/issues/9

**Comment by Marvin1412** [comment]
Thank you for the Answer!
